// GENERATED by evaluation/exports.py from results/demo_day.json. Do not edit by hand.
// date 2025-07-25  scenario heatwave  data_source synthetic_sample
#pragma once
#include <stdint.h>
// mode: 0=NORMAL, 1=PRE_COOL, 2=PEAK_REDUCE, 3=OVERRIDE
#define REPLAY_HOURS 24
static const uint8_t REPLAY_MODE[24] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 2, 0, 0, 0, 0, 0};
static const uint8_t REPLAY_FAN_PCT[24] = {40, 40, 40, 40, 40, 40, 40, 40, 40, 100, 100, 100, 75, 75, 75, 75, 75, 100, 75, 40, 40, 40, 40, 40};
static const uint8_t REPLAY_LED_GPIO[24] = {27, 27, 27, 27, 27, 27, 27, 27, 27, 25, 25, 25, 26, 26, 26, 26, 26, 32, 26, 27, 27, 27, 27, 27};
static const int16_t REPLAY_INDOOR_X10[24] = {240, 240, 240, 240, 240, 240, 240, 240, 240, 240, 234, 229, 225, 233, 242, 248, 254, 258, 255, 256, 246, 242, 241, 240};
static const uint16_t REPLAY_KWH_BASE_X100[24] = {38, 57, 60, 9, 31, 4, 33, 58, 0, 65, 159, 226, 239, 324, 306, 312, 308, 247, 167, 104, 0, 63, 6, 17};
static const uint16_t REPLAY_KWH_OPT_X100[24] = {38, 57, 60, 9, 31, 4, 33, 58, 0, 215, 309, 360, 108, 146, 138, 140, 139, 247, 75, 282, 65, 87, 15, 17};
static const uint16_t REPLAY_HOUR_MS[24] = {3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 3000, 3000, 3000, 3000, 3000};
